"use client";
import Link from "next/link";import{useEffect,useMemo,useState}from"react";import{criterionDefinitions,getPriority}from"@/lib/data";import{supabase}from"@/lib/supabase";
type Project={id:string;name:string};type Garden={id:string;project_id:string;name:string;district?:string|null};type Scores=Record<string,number>;type FilesMap=Record<string,File|null>;type PreviewMap=Record<string,string>;
export default function AssessmentPage(){const[projects,setProjects]=useState<Project[]>([]);const[gardens,setGardens]=useState<Garden[]>([]);const[projectId,setProjectId]=useState("");const[gardenId,setGardenId]=useState("");const[scores,setScores]=useState<Scores>({});const[files,setFiles]=useState<FilesMap>({});const[previews,setPreviews]=useState<PreviewMap>({});const[msg,setMsg]=useState("");const[saving,setSaving]=useState(false);
async function loadMaster(){const[p,g]=await Promise.all([supabase.from("projects").select("*").order("name"),supabase.from("gardens").select("*").order("name")]);if(p.data)setProjects(p.data);if(g.data)setGardens(g.data)}useEffect(()=>{loadMaster()},[]);
const projectGardens=gardens.filter(g=>!projectId||g.project_id===projectId);const selectedProject=projects.find(p=>p.id===projectId);const selectedGarden=gardens.find(g=>g.id===gardenId);
const criteria=useMemo(()=>criterionDefinitions.map((c,ci)=>{const itemLines=c.items.map((it,ii)=>{const key=`${ci}-${ii}`;const val=Math.min(Number(scores[key]||0),it.max);return val>0?`${it.label}: ${val}/${it.max}`:""}).filter(Boolean);const value=Math.min(c.items.reduce((sum,it,ii)=>sum+Math.min(Number(scores[`${ci}-${ii}`]||0),it.max),0),c.weight);return{name:c.name,weight:c.weight,selected:itemLines.length?itemLines.join(" + "):"لم يتم إدخال درجات",value}}),[scores]);
const score=criteria.reduce((s,i)=>s+i.value,0);const priority=getPriority(score);
function setItemScore(ci:number,ii:number,max:number,value:string){const num=Math.max(0,Math.min(Number(value||0),max));setScores(prev=>({...prev,[`${ci}-${ii}`]:num}))}
function setItemFile(ci:number,ii:number,file:File|null){const key=`${ci}-${ii}`;if(!file)return;setFiles(prev=>({...prev,[key]:file}));setPreviews(prev=>({...prev,[key]:URL.createObjectURL(file)}))}
async function uploadPhoto(assessmentId:string,criterionId:string,key:string){const file=files[key];if(!file)return null;const safe=file.name.replace(/[^\w.\-]+/g,"_");const path=`${assessmentId}/${criterionId}/${key}-${Date.now()}-${safe}`;const{error}=await supabase.storage.from("criterion-photos").upload(path,file,{upsert:true});if(error)return null;return supabase.storage.from("criterion-photos").getPublicUrl(path).data.publicUrl}
async function saveAssessment(){if(!projectId||!gardenId){setMsg("اختر المشروع والحديقة أولاً.");return}setSaving(true);setMsg("جاري الحفظ ورفع الصور...");const{data:assessment,error}=await supabase.from("garden_assessments").insert({garden_id:gardenId,garden_name:selectedGarden?.name||"",project:selectedProject?.name||"",district:selectedGarden?.district||"غير محدد",score,priority:priority.label}).select("id").single();if(error||!assessment){setMsg(error?.message||"تعذر الحفظ");setSaving(false);return}for(let ci=0;ci<criteria.length;ci++){const c=criteria[ci];const{data:criterion}=await supabase.from("assessment_criteria").insert({assessment_id:assessment.id,criterion_name:c.name,weight:c.weight,selected_label:c.selected,value:c.value}).select("id").single();if(criterion){for(let ii=0;ii<criterionDefinitions[ci].items.length;ii++){const key=`${ci}-${ii}`;const url=await uploadPhoto(assessment.id,criterion.id,key);if(url)await supabase.from("criterion_photos").insert({criterion_id:criterion.id,photo_url:url,note:`صورة بند ${criterionDefinitions[ci].items[ii].label}`})}}}setMsg(`تم حفظ التقييم بنجاح. التصنيف: أولوية ${priority.label} (${score}%).`);setSaving(false)}
return <main className="page"><section className="container"><header className="header"><div><div className="pill">📝 صفحة إدخال التقييم</div><h1>تقييم حديقة جديدة</h1><p>اختر المشروع والحديقة من القاعدة، ثم أدخل درجة كل بند وارفع صورة مستقلة لكل بند عند الحاجة.</p><div className="nav-actions"><Link className="action" href="/dashboard">عرض لوحة النتائج</Link></div></div><div className="legend"><p>النتيجة الحالية</p><div className="result-box"><div className="result-score">{score}%</div><div>أولوية {priority.label}</div><small>{priority.range} · {priority.text}</small></div></div></header><section className="form-shell"><aside className="form-card"><h2>بيانات الحديقة</h2><div className="field"><label>المشروع</label><select value={projectId} onChange={e=>{setProjectId(e.target.value);setGardenId("")}}><option value="">اختر مشروع</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="field"><label>الحديقة</label><select value={gardenId} onChange={e=>setGardenId(e.target.value)}><option value="">اختر حديقة</option>{projectGardens.map(g=><option key={g.id} value={g.id}>{g.name} - {g.district||"بدون حي"}</option>)}</select></div><button className="submit" onClick={saveAssessment} disabled={saving}>{saving?"جاري الحفظ...":"حفظ التقييم"}</button>{msg&&<p className="panel-desc">{msg}</p>}<p className="panel-desc">لإضافة مشاريع وحدائق جديدة، أضفها مؤقتًا من Supabase في جدول projects و gardens.</p></aside><section className="form-card"><h2>المعايير والبنود</h2><div className="criteria-form">{criterionDefinitions.map((criterion,ci)=><div className="criterion-form" key={criterion.name}><div className="criterion-form-head"><h3>{criterion.name}</h3><b>{criteria[ci]?.value||0}/{criterion.weight}</b></div><div className="items-grid">{criterion.items.map((item,ii)=>{const key=`${ci}-${ii}`;return <div className="item-card" key={key}><h4>{item.label}</h4><div className="item-row"><label>الدرجة / {item.max}</label><input type="number" min={0} max={item.max} value={scores[key]??""} onChange={e=>setItemScore(ci,ii,item.max,e.target.value)} placeholder="0"/></div><div className="file-mini"><label className="change-photo">{previews[key]?"تغيير الصورة":"رفع صورة للبند"}</label><input type="file" accept="image/*" onChange={e=>setItemFile(ci,ii,e.target.files?.[0]||null)}/>{previews[key]&&<div className="preview"><div className="preview-box"><img src={previews[key]} alt="معاينة"/></div></div>}</div></div>})}</div></div>)}</div></section></section></section></main>}
