"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { criterionDefinitions, getPriority } from "@/lib/data";
import { supabase } from "@/lib/supabase";
type Selections = Record<number, number[]>; type FilesByCriterion = Record<number, File[]>;
export default function AssessmentPage(){
  const [gardenName,setGardenName]=useState(""); const [project,setProject]=useState("مشروع بريمان وطيبة"); const [district,setDistrict]=useState("");
  const [selections,setSelections]=useState<Selections>({}); const [files,setFiles]=useState<FilesByCriterion>({}); const [previews,setPreviews]=useState<Record<number,string[]>>({});
  const [savedMessage,setSavedMessage]=useState(""); const [saving,setSaving]=useState(false);
  const criteria=useMemo(()=>criterionDefinitions.map((criterion,index)=>{const selectedIndexes=selections[index]||[];const selectedOptions=selectedIndexes.map((i)=>criterion.options[i]).filter(Boolean);const value=selectedOptions.reduce((sum,option)=>sum+option.value,0);return {name:criterion.name,weight:criterion.weight,selected:selectedOptions.length?selectedOptions.map((o)=>o.label).join(" + "):"لم يتم الاختيار",value:Math.min(value,criterion.weight)}}),[selections]);
  const score=criteria.reduce((sum,item)=>sum+item.value,0); const priority=getPriority(score);
  const toggleOption=(criterionIndex:number,optionIndex:number,multi?:boolean)=>setSelections((prev)=>{const current=prev[criterionIndex]||[];if(!multi)return{...prev,[criterionIndex]:[optionIndex]};const exists=current.includes(optionIndex);return{...prev,[criterionIndex]:exists?current.filter((i)=>i!==optionIndex):[...current,optionIndex]}});
  const handlePhotos=(criterionIndex:number,fileList:FileList|null)=>{if(!fileList)return;const selectedFiles=Array.from(fileList).slice(0,4);setFiles((prev)=>({...prev,[criterionIndex]:[...(prev[criterionIndex]||[]),...selectedFiles]}));setPreviews((prev)=>({...prev,[criterionIndex]:[...(prev[criterionIndex]||[]),...selectedFiles.map((file)=>URL.createObjectURL(file))]}))};
  async function uploadCriterionPhotos(assessmentId:string,criterionId:string,criterionIndex:number){const criterionFiles=files[criterionIndex]||[];const uploadedUrls:string[]=[];for(const file of criterionFiles){const safeName=file.name.replace(/[^\w.\-]+/g,"_");const path=`${assessmentId}/${criterionId}/${Date.now()}-${safeName}`;const {error}=await supabase.storage.from("criterion-photos").upload(path,file);if(error)continue;const {data}=supabase.storage.from("criterion-photos").getPublicUrl(path);if(data.publicUrl)uploadedUrls.push(data.publicUrl)}if(uploadedUrls.length)await supabase.from("criterion_photos").insert(uploadedUrls.map((url)=>({criterion_id:criterionId,photo_url:url,note:"صورة إثبات من تقييم المشرف"})))}
  const saveAssessment=async()=>{if(!gardenName.trim()){setSavedMessage("اكتب اسم الحديقة أولاً.");return}setSaving(true);setSavedMessage("جاري الحفظ ورفع الصور...");const {data:assessment,error}=await supabase.from("garden_assessments").insert({garden_name:gardenName.trim(),project,district:district.trim()||"غير محدد",score,priority:priority.label}).select("id").single();if(error||!assessment){setSavedMessage(`تعذر حفظ التقييم: ${error?.message||"خطأ غير معروف"}`);setSaving(false);return}for(let index=0;index<criteria.length;index++){const criterion=criteria[index];const {data:insertedCriterion,error:criterionError}=await supabase.from("assessment_criteria").insert({assessment_id:assessment.id,criterion_name:criterion.name,weight:criterion.weight,selected_label:criterion.selected,value:criterion.value}).select("id").single();if(!criterionError&&insertedCriterion)await uploadCriterionPhotos(assessment.id,insertedCriterion.id,index)}setSavedMessage(`تم حفظ التقييم بنجاح. التصنيف: أولوية ${priority.label} (${score}%).`);setSaving(false)};
  return <main className="page"><section className="container"><header className="header"><div><div className="pill">📝 صفحة إدخال التقييم</div><h1>تقييم حديقة جديدة</h1><p>يدخل المشرف درجات المعايير ويرفع صور إثبات الحالة. بعد الحفظ تُخزن البيانات في Supabase وتظهر في لوحة المؤشرات.</p><div className="nav-actions"><Link className="action" href="/dashboard">عرض لوحة النتائج</Link></div></div><div className="legend"><p className="legend-title">النتيجة الحالية</p><div className="result-box"><div className="result-score">{score}%</div><div>أولوية {priority.label}</div><small>{priority.range} · {priority.text}</small></div></div></header><section className="form-shell"><aside className="form-card"><h2>بيانات الحديقة</h2><div className="field"><label>اسم الحديقة</label><input value={gardenName} onChange={(e)=>setGardenName(e.target.value)} placeholder="مثال: حديقة الربيع"/></div><div className="field"><label>المشروع</label><select value={project} onChange={(e)=>setProject(e.target.value)}><option>مشروع بريمان وطيبة</option><option>مشروع الحمدانية</option><option>مشروع التحلية</option><option>مشروع الشروق</option></select></div><div className="field"><label>الحي / الموقع</label><input value={district} onChange={(e)=>setDistrict(e.target.value)} placeholder="مثال: حي الربيع"/></div><button className="submit" onClick={saveAssessment} disabled={saving}>{saving?"جاري الحفظ...":"حفظ التقييم وإظهار النتيجة"}</button>{savedMessage&&<p className="panel-desc">{savedMessage}</p>}</aside><section className="form-card"><h2>المعايير السبعة</h2><div className="criteria-form">{criterionDefinitions.map((criterion,criterionIndex)=><div className="criterion-form" key={criterion.name}><div className="criterion-form-head"><h3>{criterion.name}</h3><b>{criteria[criterionIndex]?.value||0}/{criterion.weight}</b></div><div className="options">{criterion.options.map((option,optionIndex)=>{const active=(selections[criterionIndex]||[]).includes(optionIndex);return <button key={option.label} className={`option ${active?"active":""}`} onClick={()=>toggleOption(criterionIndex,optionIndex,criterion.multi)}><b>{option.label}</b><br/><small>{option.value} درجات</small></button>})}</div><div className="filebox"><label>صور إثبات الحالة لهذا المعيار</label><input type="file" accept="image/*" multiple onChange={(e)=>handlePhotos(criterionIndex,e.target.files)}/>{!!previews[criterionIndex]?.length&&<div className="preview">{previews[criterionIndex].map((photo,idx)=><img key={idx} src={photo} alt={`صورة ${idx+1}`}/>)}</div>}</div></div>)}</div></section></section></section></main>
}
